### ISSUE TITLE
Errors running tutorials

### ISSUE THREAD

**Issue by soerenab** [theislab/sfaira#375] opened 2021-09-20 10:20 UTC
> 1) data_loader.ipynb
For context, I am setting ``` basedir = '/Users/soeren.becker/repos/sfaira/sfaira/data' ```.
The first thing that I noticed is that, in contrast to the notebook from the github repository,  ```print(ds.adata)```  returns ```None```. This is not an error but maybe it helps explaining some errors downstream.

- [x] This is because the data was not downloaded, see below. [download statement added to tutorial notebook]

> - Running ```ds.datasets['mouse_pancreas_2019_10xsequencing_thompson_004_10.1016/j.cmet.2019.01.021'].annotated```throws an error: ```KeyError: 'mouse_pancreas_2019_10xsequencing_thompson_004_10.1016/j.cmet.2019.01.021'```. My guess is that the name somehow changed as ```ds.datasets['mouse_pancreas_2019_10x3v2_thompson_004_10.1016/j.cmet.2019.01.021'].annotated``` runs and returns ```True```.

- [x] Yes indeed the data set key changed as we updated technology versions. This ID will stay fixed now and we can update the key in the tutorial. [switched the datasets used in this notebook to a fully public dataset with an up-to-date id]

> - In the next cell, ```ds.datasets['mouse_pancreas_2019_10xsequencing_thompson_004_10.1016/j.cmet.2019.01.021'].load()``` again throws a key error. However, ```ds.datasets['mouse_pancreas_2019_10x3v2_thompson_004_10.1016/j.cmet.2019.01.021'].load()```also throws an error: ```FileNotFoundError: [Errno 2] No such file or directory: '/Users/soeren.becker/repos/sfaira/sfaira/data/raw/GSE117770_RAW.tar'``` This error I could not resolve so far so I haven't run the rest of the tutorial yet.

- [x] This dataset is not downloaded yet. We need to add a download statement from the universe instance at the top of that notebook? Maybe also switch to a data set that does not have private meta data. [download statement added and dataset switched - see above]

> 2) user_interface.ipynb
- ```ui.data.obsm``` throws an error: ```AttributeError: 'DatasetInteractive' object has no attribute 'obsm'``` . 

- [x] This is trying to access adata.obsm I assume, this would be `ui.data.adata.obsm`, `ui.data` is a `Dataset`. [updated in tutorial notebook]
- [x] `KeyError: 'organism'` from calling `ui.load_model_embedding()`
- [x] `AssertionError: did not find variable names from genome container in store` from calling `ui.load_model_embedding()`

> - There are also errors downstream from there, but they might just be the result of this error, I think.

I think so too.

> 3) pbmc3k.ipynb
- (I think this first error is unrelated to sfaira as I also get this error when just running the corresponding scanpy_tutorial; just mentioning it for completion: In the final pre-sfaira cell (for me cell [31]), ```sc.pl.umap(adata, color='leiden', legend_loc='on data', title='', frameon=False)``` results in an error: ```AttributeError: 'Float64Index' object has no attribute 'add_categories'``` .)

- [x] I think the issue is that leiden in obs is float, we could address this in the tutorial by redefining that in the adata that is given to the `DatasetInteractive`. 

> - When running ```ui = sfaira.ui.UserInterface(
    custom_repo=os.path.join(model_dir_sfaira),
    sfaira_repo=False
)```, I get the following error: ```ValueError: No model weights found in ../../sfaira/sfaira/models/ Weights need to have .h5 or .data-00000-of-00001 extensionto be recognised```. This is indeed true, there are no such files under  ../../sfaira/sfaira/models/ .

- [x] ~~I think there is either an explicit download missing or a defaulting to download of weights missing.~~ This is because you do not have any weights in the local model repository which you provided. I have removed the local model repository in the tutorial.

> I am wondering whether this error occurs as I did not complete the other tutorials before? Also, in case there is an intended order in which the tutorials should be carried out (as they depend on each other's output?), it might be worthwhile to mention this here: https://sfaira.readthedocs.io/en/latest/tutorials.html
 
Thanks for the issue, @soerenab!

**Comment by tuln128** [comment] 2021-09-21 01:12
Hello,
I also got errors running the tutorial. Besides the "Float64Index" error above, the following error occur while running **ui.load_model_embedding()**:

**KeyError: 'organism'**

It was caused by the following function call:

**File "_overloaded_dict.py", line 100, in __getitem__
    return self.data[key]**

It's greatly appreciated if anyone can show me how to fix this error.

Many thanks!

**Comment by bitcometz** [comment] 2021-09-26 07:31
hello，I also got the error : **KeyError: 'organism'**

**Comment by le-ander** [comment] 2021-09-27 18:51
All errors mentioned in this issue are now addressed in the latest version of the notebooks. Some of the fixes required changen sfaira code. Version 0.3.7 will contain all the necessary changes that will allow error-free execution of the notebooks. To already get these changes now, you can install the `fix_tutorials` branch of sfaira until version 0.3.7 is released.

Thank you very much for the bug reports!

**Closed by le-ander** 2021-09-27 18:51 UTC

**Comment by le-ander** [comment] 2021-09-28 06:31
the error is raised by the download of ontology files by sfaira from here, not the download of the dataset: https://raw.githubusercontent.com/obophenotype/cell-ontology/v2021-02-01/cl.obo

**Comment by davidsebfischer** [comment] 2021-09-28 08:53
> ```
> ui.load_data(sc.datasets.pbmc3k(), gene_symbol_col='index', gene_ens_col='gene_ids')  # load your dataset into sfaira
> ```
> 
> got errors:
> 
> ```
> SSLError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /obophenotype/cell-ontology/v2021-02-01/cl.obo (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1122)')))
> ```
> 
> Could you also provide website URL to download the datasets?

It looks like your internet connection is bad (not connected?). Sfaira caches these ontology files so you do not need internet connection every time you use it, but you do need it the first time that you use meta data that requires caching.

**Comment by bitcometz** [comment] 2021-09-29 03:20
Thanks for your help, it is the problem of my internet.
